language: cpp

compiler:
  - gcc
  - clang

# Travis CI has 1.5 cores per VM, take advantage of it
# But first, the makefiles have to be fixed: all plugins are using the same .o's
#env:
#  - MAKEFLAGS="-j 2"

before_install:
  - git submodule update --init --recursive
script: make CONFIG=debug
